export const categories = [
  { slug: "vuelos-hotel", name: "Vuelos + Hotel", icon: "✈️", color: "bg-blue-100 text-blue-700" },
  { slug: "solo-hotel", name: "Solo Hotel", icon: "🏨", color: "bg-purple-100 text-purple-700" },
  { slug: "cruceros", name: "Cruceros", icon: "🚢", color: "bg-cyan-100 text-cyan-700" },
  { slug: "circuitos", name: "Circuitos", icon: "🗺️", color: "bg-green-100 text-green-700" },
  { slug: "aventura", name: "Aventura", icon: "🏔️", color: "bg-orange-100 text-orange-700" },
  { slug: "novios", name: "Novios", icon: "💍", color: "bg-pink-100 text-pink-700" },
  { slug: "mice", name: "MICE", icon: "🏢", color: "bg-gray-100 text-gray-700" },
  { slug: "estudios", name: "Estudios", icon: "📚", color: "bg-yellow-100 text-yellow-700" },
  { slug: "escapadas", name: "Escapadas", icon: "🎒", color: "bg-teal-100 text-teal-700" },
  { slug: "accesibles", name: "Accesibles", icon: "♿", color: "bg-indigo-100 text-indigo-700" },
];

export const agencies = [
  {
    id: 1,
    name: "Viajes Europa",
    slug: "viajes-europa",
    logo: null,
    description: "Especialistas en circuitos por Europa desde 2005. Más de 50 destinos y experiencias únicas.",
    verified: true,
    licenseNumber: "CV-12345-MA",
    website: "https://viajes-europa.example.com",
    phone: "+34 912 345 678",
    email: "info@viajes-europa.example.com",
    country: "España",
    city: "Madrid",
    createdAt: "2020-01-15",
    totalListings: 12,
    averageRating: 4.7,
    yearsActive: 4,
    listings: [],
  },
  {
    id: 2,
    name: "Caribe Directo",
    slug: "caribe-directo",
    logo: null,
    description: "Tu puerta al Caribe. Paquetes todo incluido, cruceros y escapadas de ensueño.",
    verified: true,
    licenseNumber: "CV-67890-MA",
    website: "https://caribe-directo.example.com",
    phone: "+34 933 456 789",
    email: "hola@caribe-directo.example.com",
    country: "España",
    city: "Barcelona",
    createdAt: "2019-03-10",
    totalListings: 8,
    averageRating: 4.5,
    yearsActive: 5,
    listings: [],
  },
];

export const featuredListings = [
  {
    id: 1,
    title: "Circuito Roma, Florencia y Venecia 7 días",
    slug: "circuito-roma-florencia-venecia-7-dias",
    description: "Descubre las joyas de Italia en un circuito guiado de 7 días. Alojamiento en hoteles 4*, desayuno incluido, vuelos desde Madrid o Barcelona.",
    shortDescription: "Circuito por Italia con guía en español",
    price: 899,
    originalPrice: 1099,
    currency: "EUR",
    durationDays: 7,
    departureDates: ["2026-05-15", "2026-06-01", "2026-06-15"],
    destination: "Italia",
    categoryId: 4,
    agencyId: 1,
    agencyName: "Viajes Europa",
    agencySlug: "viajes-europa",
    featured: true,
    status: "active",
    coverImage: "https://images.unsplash.com/photo-1529260830199-42c42dda5f3d?w=800",
    rating: 4.8,
    reviewCount: 124,
    maxTravelers: 25,
    images: [
      { url: "https://images.unsplash.com/photo-1529260830199-42c42dda5f3d?w=1200", alt: "Roma" },
      { url: "https://images.unsplash.com/photo-1541363111435-5c1b7d867904?w=1200", alt: "Florencia" },
      { url: "https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=1200", alt: "Venecia" },
    ],
  },
  {
    id: 2,
    title: "Crucero por el Caribe 10 días todo incluido",
    slug: "crucero-caribe-10-dias-todo-incluido",
    description: "Navega por las aguas cristalinas del Caribe. Todo incluido: comidas, bebidas, entretenimiento y excursiones en puerto.",
    shortDescription: "Crucero todo incluido por el Caribe",
    price: 1299,
    originalPrice: 1599,
    currency: "EUR",
    durationDays: 10,
    departureDates: ["2026-05-20", "2026-06-10"],
    destination: "Caribe",
    categoryId: 3,
    agencyId: 2,
    agencyName: "Caribe Directo",
    agencySlug: "caribe-directo",
    featured: true,
    status: "active",
    coverImage: "https://images.unsplash.com/photo-1544144433-d50aff500b91?w=800",
    rating: 4.6,
    reviewCount: 89,
    maxTravelers: 200,
    images: [
      { url: "https://images.unsplash.com/photo-1544144433-d50aff500b91?w=1200", alt: "Caribe" },
      { url: "https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=1200", alt: "Crucero" },
    ],
  },
  {
    id: 3,
    title: "Escapada fin de semana a París",
    slug: "escapada-fin-de-semana-paris",
    description: "Vive la magia de París en un fin de semana. Vuelo + hotel en el centro, cerca de la Torre Eiffel.",
    shortDescription: "París en fin de semana",
    price: 299,
    originalPrice: 399,
    currency: "EUR",
    durationDays: 3,
    departureDates: ["2026-05-10", "2026-05-17", "2026-05-24"],
    destination: "Francia",
    categoryId: 9,
    agencyId: 1,
    agencyName: "Viajes Europa",
    agencySlug: "viajes-europa",
    featured: true,
    status: "active",
    coverImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    rating: 4.4,
    reviewCount: 56,
    maxTravelers: 30,
    images: [
      { url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200", alt: "París" },
    ],
  },
];

export const listings = [...featuredListings, ...featuredListings.map((l, i) => ({
  ...l,
  id: l.id + 3 + i,
  slug: `${l.slug}-v${i + 2}`,
  featured: false,
  price: l.price - 50,
}))];
